#!/usr/bin/env python3
"""
Create GitHub Pull Request for worktree feature branch.

Usage:
    python scripts/worktree_create_pr.py <worktree-id>

Creates PR with:
- Title from branch name or custom title
- Body with summary of changes
- Target: ALWAYS main (hardcoded, not current branch)
- NO auto-merge (requires human approval)
- Returns PR number and URL

Note: PR always targets main, regardless of which branch
the worktree was created from.
"""

import os
import sys
import json
import subprocess
from pathlib import Path
from typing import Dict, Optional

# Path to worktree registry
REGISTRY_DIR = Path.home() / ".claude" / "worktrees"
REGISTRY_FILE = REGISTRY_DIR / "registry.json"

def load_registry() -> Dict:
    """Load worktree registry from file."""
    if not REGISTRY_FILE.exists():
        print("❌ Worktree registry not found.")
        return {}

    with open(REGISTRY_FILE, 'r') as f:
        return json.load(f)

def save_registry(registry: Dict):
    """Save worktree registry to file."""
    with open(REGISTRY_FILE, 'w') as f:
        json.dump(registry, f, indent=2)

def get_worktree_info(worktree_id: str, registry: Dict) -> Optional[Dict]:
    """Get worktree information from registry."""
    if worktree_id not in registry:
        print(f"❌ Worktree '{worktree_id}' not found in registry")
        return None

    return registry[worktree_id]

def create_pr(worktree_id: str):
    """Create GitHub Pull Request to main (always main)."""

    # Load registry
    registry = load_registry()
    if not registry:
        sys.exit(1)

    # Get worktree info
    worktree_info = get_worktree_info(worktree_id, registry)
    if not worktree_info:
        sys.exit(1)

    branch_name = worktree_info['branch']
    current_branch = worktree_info['base_branch']  # Where worktree came from (for info only)
    worktree_path = Path(worktree_info['path'])

    # PR target is ALWAYS main
    pr_target = "main"

    print(f"\n📝 Creating Pull Request")
    print(f"   Source branch: {branch_name}")
    print(f"   Created from: {current_branch}")
    print(f"   Target branch: {pr_target} (always main)")

    # Change to worktree directory
    original_dir = os.getcwd()
    os.chdir(worktree_path)

    # Get commit summary for PR body (compare against main, not current branch)
    result = subprocess.run(
        ['git', 'log', '--oneline', f'origin/{pr_target}..HEAD'],
        capture_output=True,
        text=True
    )
    commits = result.stdout.strip()

    # Generate PR title from branch name
    feature_name = worktree_info['feature_name']
    pr_title = feature_name.replace('-', ' ').replace('_', ' ').title()

    # Generate PR body
    pr_body = f"""## Summary
Changes from feature branch `{branch_name}` to `{pr_target}`

## Source
- Created from branch: `{current_branch}`
- Merging to: `{pr_target}`

## Commits
```
{commits}
```

## Test Results
- ✅ Unit tests passed (Step 5)
- ✅ Code review approved (Step 6)
- ✅ Integration tests passed (Step 8)
- ✅ Final integration test passed (Step 11)

---
🤖 Generated by Claude Code worktree workflow
"""

    # Create PR to main (hardcoded, not dynamic)
    print(f"\n🔄 Creating PR: {branch_name} → {pr_target}")
    try:
        result = subprocess.run(
            [
                'gh', 'pr', 'create',
                '--title', pr_title,
                '--body', pr_body,
                '--base', pr_target,  # ALWAYS main
                '--head', branch_name
            ],
            capture_output=True,
            text=True,
            check=True
        )

        # Extract PR URL from output
        pr_url = result.stdout.strip()

        # Get PR number
        result = subprocess.run(
            ['gh', 'pr', 'view', '--json', 'number'],
            capture_output=True,
            text=True,
            check=True
        )
        pr_data = json.loads(result.stdout)
        pr_number = pr_data['number']

        print(f"✅ PR created: {pr_url}")
        print(f"   PR #{pr_number}: {pr_title}")

        # Update registry with PR info
        worktree_info['pr'] = {
            'number': pr_number,
            'url': pr_url,
            'title': pr_title
        }
        worktree_info['status'] = 'pr_created'

        os.chdir(original_dir)
        registry[worktree_id] = worktree_info
        save_registry(registry)

        print(f"\n⏳ Waiting for human review and approval...")
        print(f"   Once approved and merged, cleanup will run automatically.")

        print(f"\n📋 Next Steps:")
        print(f"1. Review PR in GitHub: {pr_url}")
        print(f"2. Approve and merge PR manually")
        print(f"3. Run polling: python scripts/worktree_poll_pr.py {worktree_id}")

    except subprocess.CalledProcessError as e:
        os.chdir(original_dir)
        print(f"❌ Failed to create PR: {e.stderr}")
        sys.exit(1)

def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/worktree_create_pr.py <worktree-id>")
        print("\nExample:")
        print("  python scripts/worktree_create_pr.py worktree-01")
        sys.exit(1)

    worktree_id = sys.argv[1]

    print("=" * 70)
    print("PR Manager - Create Pull Request")
    print("=" * 70)

    create_pr(worktree_id)

    print("\n" + "=" * 70)
    print("✅ PR Created Successfully")
    print("=" * 70)

if __name__ == "__main__":
    main()
